### ISSUE TITLE
Suchfunktion in der Galerie - Bestätigen

### ISSUE THREAD

**Issue by mai-space** [Inf166/WDSS19-Praxisarbeit#11]
Wenn man in der Galerie Christi sucht, wird nichts angezeigt. Bestätigt man die Suche via Bildschirmtastatur <Return> dann landet man bei dem Scanner und die Seite wurde neu geladen.

**Comment by ghost** [comment]
Die "Bestätigung der Suche" führt einen Form-Submit und somit eine POST-Method aus. Dadurch wird die Seite neu geladen. Dies sollte sich mittels JQuery verhindern lassen.

Das Problem mit der Suche liegt auf den ersten Blick daran, dass nur das erste Wort des Titels bei der Suche berücksichtigt wird. Ich erstelle dafür eine eigene Issue.

**Comment by ghost** [comment]
Behoben in https://github.com/Inf166/WDSS19-Praxisarbeit-CDAA/commit/f1c0da446da324692a1cbceed373764f15e6a4e4
