### ISSUE TITLE
Seiteninhalt springt

### ISSUE THREAD

**Issue by mai-space** [Inf166/WDSS19-Praxisarbeit#6]
Beim wechseln von den Seiten

- Galerie -> Info
- Info -> Imageview
Springt der Inhalt nach oben und unten weil die Bilder zu lange laden

Möglicher Fix mit Platzhaltern? #lazyload

**Comment by ghost** [comment]
Möglicherweise unabhängig vom Fehler, aber bitte nach https://github.com/Inf166/WDSS19-Praxisarbeit-CDAA/commit/8d82ace94cc6e96948f3f7cd6708be679ba3c453 nochmal testen.

**Comment by IceQ1337** [comment]
Ich kann den Fehler leider gar nicht erst reproduzieren.

Die Seite erst zu wechseln nachdem das HTML aufgebaut wurde, würde den Fehler nicht beheben, da die Ladezeit der Bilder unverändert bleiben würde.

**Comment by ghost** [comment]
Ich kann den Fehler leider gar nicht erst reproduzieren.

Die Seite erst zu wechseln nachdem das HTML aufgebaut wurde, würde den Fehler nicht beheben, da die Ladezeit der Bilder unverändert bleiben würde.

**Comment by mai-space** [comment]
Momentan taucht der Fehler bei Firefox und auf dem Handy nicht mehr auf - daher vorerst closed
