### ISSUE TITLE
Position des "Zurück"-Buttons

### ISSUE THREAD

**Issue by mai-space** [Inf166/WDSS19-Praxisarbeit#8]
Bei dem Öffnen der Extrabilder zu einem Gemälde befindet sich zurzeit ein kleiner Button mit Pfeil oben links - dieser ist relativ klein aber doch gut sichtbar, sollte dieser nicht besser unten rechts positioniert sein? 
Im Sinne der Zugänglichkeit und Gebrauchstauglichkeit

**Comment by ghost** [comment]
Nach der Bewegungs-/Textrichtung bewegt man sich von links nach rechts, weshalb ein "Zurück"-Pfeil auch nach links ausgerichtet ist. Diesen rechts zu positionieren wäre ungewöhnlich. Meiner Meinung nach hast du ihn oben links gut positioniert.

**Comment by ghost** [comment]
Position des Buttons wird vorerst beibehalten.
