### ISSUE TITLE
Bildvergrößerung & Zoomfunktion

### ISSUE THREAD

**Issue by ghost** [Inf166/WDSS19-Praxisarbeit#9]
Alle Bilder in der erweiterten Bildansicht sollen im Großformat angezeigt werden können.

**Comment by mai-space** [comment]
Ich habe noch keine Möglichkeit gefunden das komplette Gemälde als 4k Bild runterzuladen - die scheinen aus Einzelbildern zu bestehen... was es kompliziert macht für die Inklusion dieser...

**Comment by ghost** [comment]
Obligatorische Bildvergrößerung wurde mittels Lightbox implementiert. Lightbox v2 beinhaltet keine Zoomfunktion, diese ist aber für v3 geplant. Wir beschränken uns für das Projekt auf diese Lösung.

> Ich habe noch keine Möglichkeit gefunden das komplette Gemälde als 4k Bild runterzuladen - die scheinen aus Einzelbildern zu bestehen... was es kompliziert macht für die Inklusion dieser...

Für Demonstrationszwecke sollte ausreichen, die vorhandenen Bilder zu laden.
